// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getUserByCognitoSub = `-- name: GetUserByCognitoSub :one
SELECT id, cognito_sub, email, created_at, updated_at, deleted_at
FROM users
WHERE cognito_sub = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByCognitoSub(ctx context.Context, cognitoSub string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByCognitoSub, cognitoSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, cognito_sub, email, created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertUserByCognitoSub = `-- name: UpsertUserByCognitoSub :one
INSERT INTO users (cognito_sub, email)
VALUES ($1, $2)
ON CONFLICT (cognito_sub) DO UPDATE SET
    email = COALESCE(EXCLUDED.email, users.email),
    deleted_at = NULL,
    updated_at = now()
RETURNING id, cognito_sub, email, created_at, updated_at, deleted_at
`

type UpsertUserByCognitoSubParams struct {
	CognitoSub string         `json:"cognito_sub"`
	Email      sql.NullString `json:"email"`
}

func (q *Queries) UpsertUserByCognitoSub(ctx context.Context, arg UpsertUserByCognitoSubParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByCognitoSub, arg.CognitoSub, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
