// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type PlaidItem struct {
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
	PublicToken     string         `json:"public_token"`
	AccessToken     string         `json:"access_token"`
	ItemID          sql.NullString `json:"item_id"`
	InstitutionID   sql.NullString `json:"institution_id"`
	InstitutionName sql.NullString `json:"institution_name"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type PlaidItemsAudit struct {
	ID          int64          `json:"id"`
	PublicToken sql.NullString `json:"public_token"`
	Action      sql.NullString `json:"action"`
	ChangedAt   sql.NullTime   `json:"changed_at"`
}

type PlaidLinkSession struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
	ExpiresAt        time.Time      `json:"expires_at"`
	PlaidRequestID   string         `json:"plaid_request_id"`
	PlaidEnvironment string         `json:"plaid_environment"`
	InitialProducts  sql.NullString `json:"initial_products"`
	CreatedAt        time.Time      `json:"created_at"`
}

type User struct {
	ID         int64          `json:"id"`
	CognitoSub string         `json:"cognito_sub"`
	Email      sql.NullString `json:"email"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
}
