// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type PlaidItem struct {
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
	PlaidItemID     string         `json:"plaid_item_id"`
	AccessToken     string         `json:"access_token"`
	InstitutionID   sql.NullString `json:"institution_id"`
	InstitutionName sql.NullString `json:"institution_name"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type PlaidItemsAudit struct {
	ID          int64          `json:"id"`
	PlaidItemID sql.NullString `json:"plaid_item_id"`
	Action      sql.NullString `json:"action"`
	ChangedAt   sql.NullTime   `json:"changed_at"`
}

type User struct {
	ID         int64          `json:"id"`
	CognitoSub string         `json:"cognito_sub"`
	Email      sql.NullString `json:"email"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
}
