// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plaid_link_session.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const insertPlaidLinkSession = `-- name: InsertPlaidLinkSession :one
INSERT INTO plaid_link_sessions (user_id, expires_at, plaid_request_id, plaid_environment, initial_products)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, expires_at, plaid_request_id, plaid_environment, initial_products, created_at
`

type InsertPlaidLinkSessionParams struct {
	UserID           int64          `json:"user_id"`
	ExpiresAt        time.Time      `json:"expires_at"`
	PlaidRequestID   string         `json:"plaid_request_id"`
	PlaidEnvironment string         `json:"plaid_environment"`
	InitialProducts  sql.NullString `json:"initial_products"`
}

func (q *Queries) InsertPlaidLinkSession(ctx context.Context, arg InsertPlaidLinkSessionParams) (PlaidLinkSession, error) {
	row := q.db.QueryRowContext(ctx, insertPlaidLinkSession,
		arg.UserID,
		arg.ExpiresAt,
		arg.PlaidRequestID,
		arg.PlaidEnvironment,
		arg.InitialProducts,
	)
	var i PlaidLinkSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.PlaidRequestID,
		&i.PlaidEnvironment,
		&i.InitialProducts,
		&i.CreatedAt,
	)
	return i, err
}
